# Site settings
title: Two minute spates
subtitle: Levelling up in ALL the things
author: Jonathan R Wallace
description: Entrepreneurship and software development in Ruby, Rails, javascript, Clojure, Go, Objective-C, iOS. Some other life stuff too.
url: http://blog.jonathanrwallace.com
baseurl: ""

# Theme settings
remote_theme: poole/hyde
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Hyde theme settings
sidebar-about-description: "Levelling up in ALL the things"
version: 2.0.0
theme_color: theme-base-08

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"
excerpt_separator: "<!--more-->"
excerpt_link: "Read on &rarr;"

# Date format
date_format: "%B %-d, %Y"

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "home"

# GitHub metadata
github: [metadata]
