# Site settings
title: Two minute spates
subtitle: Levelling up in ALL the things
author: Jonathan R Wallace
description: Entrepreneurship and software development in Ruby, Rails, javascript, Clojure, Go, Objective-C, iOS. Some other life stuff too.
url: http://blog.jonathanrwallace.com
baseurl: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"
excerpt_separator: "<!--more-->"
excerpt_link: "Read on &rarr;"

# Date format
# Default date format is "ordinal" (resulting in "July 22nd 2007")
date_format: "ordinal"

# RSS settings
subscribe_rss: /atom.xml
email:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false

# Add repository information
repository: "wallace/wallace.github.com"

# Pagination settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
